#!/usr/bin/env bash
# Generates docker-compose.dev.yml from codex.yml.
# The dev compose only runs the DB; the app runs on your laptop via `dotnet run`
# so you keep hot reload and breakpoints.
#
# Requires: yq (brew install yq)
# Usage: scripts/gen-dev-compose.sh > docker-compose.dev.yml
set -euo pipefail

MANIFEST="${MANIFEST:-codex.yml}"
command -v yq >/dev/null || { echo "yq not found. Install: brew install yq" >&2; exit 1; }
[[ -f "$MANIFEST" ]] || { echo "$MANIFEST not found" >&2; exit 1; }

SERVICE=$(yq -r '.service' "$MANIFEST")
HAS_DB=$(yq -r 'has("database")' "$MANIFEST")
DB_TYPE=$(yq -r '.database.type // ""' "$MANIFEST")
DB_VERSION=$(yq -r '.database.version // "16"' "$MANIFEST")

if [[ "$HAS_DB" != "true" ]]; then
  echo "codex.yml has no database: section; nothing to generate" >&2
  exit 0
fi

if [[ "$DB_TYPE" != "postgres" ]]; then
  echo "unsupported database.type: $DB_TYPE" >&2
  exit 1
fi

cat <<YAML
# Generated by scripts/gen-dev-compose.sh from ${MANIFEST}. Do not edit by hand.
# Runs only the database. Run the app on your laptop with:
#   dotnet run
services:
  db:
    image: postgres:${DB_VERSION}
    environment:
      POSTGRES_DB: ${SERVICE}
      POSTGRES_USER: ${SERVICE}
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SERVICE} -d ${SERVICE}"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  pgdata:
YAML
